[package]
name = "ase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
hound = "3.5.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
realfft = "3.3.0"
rustfft = "6.2.0"
